# Generated by Django 4.0.2 on 2022-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(default='0'),
        ),
    ]
